execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set tabstop=2
set colorcolumn=80 
set term=screen-256color
set mouse=a
set timeoutlen=1000 ttimeoutlen=0

imap <C-K>  <C-O>%<C-O>%<right><space>  
imap jj <ESC>

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

set runtimepath^=~/.vim/bundle/ctrlp.vim

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

set nocompatible
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-commentary'
Plugin 'steffanc/cscopemaps.vim'
Plugin 'terryma/vim-smooth-scroll'
call vundle#end()
set foldmethod=indent
set foldlevel=99 
set expandtab 
set shiftwidth=3
set modeline
set modelines=1
set t_Co=256
syntax enable
colorscheme harlequin
let mapleader="\<Space>"

